version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile.prod
    ports:
      - "5454:5454"
    environment:
      - NODE_ENV=production
      - PORT=5454
      - BASE_URL = http://apalabajar.com
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: dockerfile.prod
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
      - REACT_APP_BASE_URL=http://apalabajar.com:5454/api
    networks:
      - app-network
networks:
  app-network:
    driver: bridge
