version: '3.8'

services:
  api:
    build:
      context: ./api
      dockerfile: dockerfile.prod
    container_name: backend-api
    ports:
      - "5454:5454"
    environment:
      - NODE_ENV=production
      - PORT=5454
      - BASE_URL=http://apalabajar.com  # Removed space around '='
    networks:
      - app-network

  client:
    build:
      context: ./client
      dockerfile: dockerfile.prod
    container_name: front-end
    ports:
      - "80:80"
    environment:
      - NODE_ENV=production
    depends_on:
      - api
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
