// aapalabajar@gmail.com
// 9975631919

import React from 'react';
import './TermsOfUse.css';

const TermsOfUse = () => {
    return (
        <div className="return-policy">
          <h1>Apala Bajar Terms of Use</h1>
    
          <h2>Introduction</h2>
          <p>
          This document is an electronic record in terms of the Information Technology Act, 2000 and rules there under as applicable and the amended provisions pertaining to electronic records in various statutes as amended by the Information Technology Act, 2000. This electronic record is generated by a computer system and does not require any physical or digital signatures.          </p>
          <p>This document is published in accordance with the provisions of Rule 3 (1) of the Information Technology (Intermediaries guidelines) Rules, 2011 that require publishing the rules and regulations, privacy policy, and Terms of Use for access or usage of domain name [www.apalabajar.com] ("Website"), including the related mobile site and mobile application (hereinafter referred to as "Platform").</p>
         
         <p>The Platform is owned by Apala Bajar Private Limited, a company incorporated under the Companies Act, 1956 with its registered office at [Inserting Address Here].</p>
         <p>Your use of the Platform and services and tools are governed by the following terms and conditions ("Terms of Use") as applicable to the Platform including the applicable policies which are incorporated herein by way of reference. If You transact on the Platform, You shall be subject to the policies that are applicable to the Platform for such transaction. By mere use of the Platform, You shall be contracting with Apala Bajar Private Limited and these terms and conditions including the policies constitute Your binding obligations, with Apala Bajar.</p>
          
          <p>For the purpose of these Terms of Use, wherever the context so requires "You" or "User" shall mean any natural or legal person who has agreed to become a buyer on the Platform by providing Registration Data while registering on the Platform as Registered User using the computer systems. Apala Bajar allows the User to surf the Platform or making purchases without registering on the Platform. The term "We", "Us", "Our" shall mean Apala Bajar Private Limited.</p>
          <p>ACCESSING, BROWSING, OR OTHERWISE USING THE SITE INDICATES YOUR AGREEMENT TO ALL THE TERMS AND CONDITIONS UNDER THESE TERMS OF USE, SO PLEASE READ THE TERMS OF USE CAREFULLY BEFORE PROCEEDING. By impliedly or expressly accepting these Terms of Use, You also accept and agree to be bound by Apala Bajar Policies (including but not limited to Privacy Policy available at [Privacy]) as amended from time to time.</p>
          <h3>Membership Eligibility</h3>
          <p>
          Transaction on the Platform is available only to persons who can form legally binding contracts under Indian Contract Act, 1872. Persons who are "incompetent to contract" within the meaning of the Indian Contract Act, 1872 including un-discharged insolvents, etc. are not eligible to use the Platform. If you are a minor i.e. under the age of 18 years, you may use the Platform or access content on the Platform only under the supervision and prior consent/permission of a parent or legal guardian.          </p>
          <p>As a minor if you wish to transact on the Platform, such transaction on the Platform may be made by your legal guardian or parents. Apala Bjar reserves the right to terminate your membership and/or refuse to provide you with access to the Platform if it is brought to Apala Bajar's notice or if it is discovered that You are under the age of 18 years and transacting on the Platform.</p>
          <h2>Your Account and Registration Obligations
          </h2>

<p>If You use the Platform, You shall be responsible for maintaining the confidentiality of your Display Name and Password and You shall be responsible for all activities that occur under your Display Name and Password. You agree that if You provide any information that is untrue, inaccurate, not current or incomplete or We have reasonable grounds to suspect that such information is untrue, inaccurate, not current or incomplete, or not in accordance with these Terms of Use, We shall have the right to indefinitely suspend or terminate or block access of your membership on the Platform and refuse to provide You with access to the Platform.</p>

<p>Your mobile phone number and/or e-mail address is treated as Your primary identifier on the Platform. It is your responsibility to ensure that Your mobile phone number and your email address is up to date on the Platform at all times. You agree to notify Us promptly if your mobile phone number or e-mail address changes by updating the same on the Platform through a onetime password verification.</p>

<p>You agree that Apala Bajar shall not be liable or responsible for the activities or consequences of use or misuse of any information that occurs under your Account in cases, including, where You have failed to update Your revised mobile phone number and/or e-mail address on the Website Platform.</p>

<p>If You share or allow others to have access to Your account on the Platform ("Account"), by creating separate profiles under Your Account, or otherwise, they will be able to view and access Your Account information. You shall be solely liable and responsible for all the activities undertaken under Your Account, and any consequences therefrom.
</p>
<p>You must maintain confidentiality of the account information and for all the activities that occur under Your account. You must not share your login details, i.e., username and password of Your account with any other person, else it would be considered breach of this Terms of Use.
</p>

          <ol><h3>You agree to:</h3> 
            <li>Ensure that You successfully log out from Your account at the end of each session.</li>
            <li>Immediately notify Apala Bajar of any unauthorized use of Your account. If there is reason to believe that there is likely to be a breach of security or misuse of Your account, We may request You to change the password or we may suspend Your account without any liability to Apala Bajar, for such period of time as we deem appropriate in the circumstances. We shall not be liable for any loss or damage arising from Your failure to comply with this provision.</li>
          </ol>
          
          <h2>Communications</h2>
          <p>
          When You use the Platform or send emails or other data, information or communication to us, You agree and understand that You are communicating with Us through electronic records and You consent to receive communications via electronic records from Us periodically and as and when required. We may communicate with you by email or by such other mode of communication, electronic or otherwise.
          </p>
          <h2>Platform for Transaction and Communication
          </h2>
          <p>
          The Platform enables the Buyer and Seller to transact on the Platform. Apala Bajar is not and cannot be a party to or control in any manner any transaction between the Platform's Users.
          </p>
          <ol><h3>Henceforward:</h3>
            <li> All commercial/contractual terms are offered by and agreed to between Buyers and Sellers alone. The commercial/contractual terms include without limitation price, shipping costs, payment methods, payment terms, date, period, and mode of delivery, warranties related to products and services, and after-sales services related to products and services. Apala Bajar does not have any control or does not determine or advise or in any way involve itself in the offering or acceptance of such commercial/contractual terms between the Buyers and Sellers. All discounts, offers (including exchange offers) are by the Seller/Brand and not by Apala Bajar.
            </li>
            <li> Placement of order by a Buyer with Seller on the Platform is an offer to buy the product(s) in by the Buyer to the Seller and it shall not be construed as Seller's acceptance of Buyer's offer to buy the product(s) ordered. The Seller retains the right to cancel any such order placed by the Buyer, at its sole discretion and the Buyer shall be intimated of the same by way of an email/SMS. Any transaction price paid by Buyer in case of such cancellation by Seller, shall be refunded to the Buyer. Further, the Seller may cancel an order wherein the quantities exceed the typical individual consumption. This applies both to the number of products ordered within a single order and the placing of several orders for the same product where the individual orders comprise a quantity that exceeds the typical individual consumption. What comprises a typical individual's consumption quantity limit shall be based on various factors and at the sole discretion of the Seller and may vary from individual to individual.

            </li>
            <li> Apala Bajar does not make any representation or Warranty as to specifics (such as quality, value, salability, etc.) of the products or services proposed to be sold or offered to be sold or purchased on the Platform. Apala Bajar does not implicitly or explicitly support or endorse the sale or purchase of any products or services on the Platform. Apala Bajar accepts no liability for any errors or omissions, whether on behalf of itself or third parties.
            </li>
            <li> Apala Bajar is not responsible for any non-performance or breach of any contract entered into between Buyers and Sellers. Apala Bajar cannot and does not guarantee that the concerned Buyers and/or Sellers will perform any transaction concluded on the Platform. Apala Bajar shall not and is not required to mediate or resolve any dispute or disagreement between Buyers and Sellers.
            </li>
            <li> Apala Bajar does not make any representation or warranty as to the item-specifics (such as legal title, creditworthiness, identity, etc.) of any of its Users. You are advised to independently verify the bona fides of any particular User that You choose to deal with on the Platform and use Your best judgment in that behalf.
            </li>
            <li> Apala Bajar does not at any point of time during any transaction between Buyer and Seller on the Platform come into or take possession of any of the products or services offered by Seller nor does it at any point gain title to or have any rights or claims over the products or services offered by Seller to Buyer.
            </li>
            <li> At no time shall Apala Bajar hold any right, title or interest over the products nor shall Apala Bajar have any obligations or liabilities in respect of such contract entered into between Buyers and Sellers. Apala Bajar is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back-ordered.
            </li>
            <li> The Platform is only a platform that can be utilized by Users to reach a larger base to buy and sell products or services. Apala Bajar is only providing a platform for communication and it is agreed that the contract for sale of any of the products or services shall be a strictly bipartite contract between the Seller and the Buyer.
            </li>
            <li> At no time shall Apala Bajar hold any right, title, or interest over the products nor shall Apala Bajar have any obligations or liabilities in respect of such contract.
            </li>
            <li> Apala Bajar is not responsible for unsatisfactory or delayed performance of services or damages or delays as a result of products which are out of stock, unavailable or back-ordered.

            </li>
            <li>You shall independently agree upon the manner and terms and conditions of delivery, payment, insurance etc. with the seller(s) that You transact with.
            </li>
          </ol>
          
          <h3>Disclaimer of Warranties and Liability
          </h3>
          <p>
          You expressly understand and agree that, to the maximum extent permitted by applicable law:
          </p>
          <p>The platform, services, and other materials are provided by Apala Bajar on an "as is" basis without warranty of any kind, express, implied, statutory or otherwise, including the implied warranties of title, non-infringement, merchantability or fitness for a particular purpose. Without limiting the foregoing, Apala Bajar makes no warranty that 
          </p>
          <ol>
            <li>The Platform or the services will meet Your requirements or Your use of the Platform will be uninterrupted, timely, secure or error-free </li>
            <li>The results that may be obtained from the use of the Platform or services will be effective, accurate or reliable. </li>
            <li>The quality of the Platform or services will meet Your expectations. </li>
            <li>Any errors or defects in the Platform or services will be corrected. No advice or information, whether oral or written, obtained by You from Apala Bajar or through or from use of the services shall create any warranty not expressly stated in the terms of use.</li>
          </ol>
          <p>
          Apala Bajar will not be liable for any loss that you may incur as a consequence of unauthorized use of Your account or account information in connection with the Platform or any services or materials, either with or without your knowledge. Apala Bajar has endeavored to ensure that all the information on the Platform is correct, but Apala Bajar neither warrants nor makes any representations regarding the quality, accuracy or completeness of any data, information, product or service. Apala Bajar shall not be responsible for the delay or inability to use the Platform or related functionalities, the provision of or failure to provide functionalities, or for any information, software, products, functionalities and related graphics obtained through the Platform, or otherwise arising out of the use of the Platform, whether based on contract, tort, negligence, strict liability or otherwise. Further, Apala Bajar shall not be held responsible for non-availability of the Platform during periodic maintenance operations or any unplanned suspension of access to the Platform that may occur due to technical reasons or for any reason beyond Apala Bajar's control. You understand and agree that any material or data downloaded or otherwise obtained through the Platform is done entirely at your own discretion and risk and you will be solely responsible for any damage to your computer systems or loss of data that results from the download of such material or data. Apala Bajar is not responsible for any typographical error leading to an invalid coupon. Apala Bajar accepts no liability for any errors or omissions, with respect to any information provided to you whether on behalf of itself or third parties.
          </p>
          
          <h2>Indemnification and Limitation of Liability
          </h2>
         
          <p>
          You agree to indemnify, defend and hold harmless Apala Bajar from and against any and all losses, liabilities, claims, damages, demands, costs and expenses (including legal fees and disbursements in connection therewith and interest chargeable thereon) asserted against or incurred by Apala Bajar that arise out of, result from, or may be payable by virtue of, any breach or non-performance of any representation, warranty, covenant or agreement made or obligation to be performed by You pursuant to these Terms of Use. Further, You agree to hold Apala Bajar harmless against any claims made by any third party due to, or arising out of, or in connection with, Your use of the Platform, any misrepresentation with respect to the data or information provided by You, Your violation of the Terms of Use, or Your violation of any rights of another, including any intellectual property rights.
          </p>
          <p>
          In no event shall Apala Bajar, its officers, directors, employees, partners or suppliers be liable to You, the seller or any third party for any special, incidental, indirect, consequential or punitive damages whatsoever, including those resulting from loss of use, data or profits, whether or not foreseeable or whether or not Apala Bajar has been advised of the possibility of such damages, or based on any theory of liability, including breach of contract or warranty, negligence or other tortious action, or any other claim arising out of or in connection with Your use of or access to the Platform, services or materials.
          </p>
          <p>Apala Bajar shall not be responsible or liable in any manner to the Users for any losses, damage, injuries or expenses incurred by You as a result of any disclosures made by Apala Bajar, where You have consented to the making of such disclosures by Apala Bajar. If You have opted out of receiving marketing emails from Apala Bajar, You may still receive transactional emails from Apala Bajar about Your account or purchases made on the Platform. 
          </p>
          
          <h4>Selling</h4>
         
          <p>As a registered seller, you are allowed to list item(s) for sale on the Platform in accordance with the Policies which are incorporated by way of reference in this Terms of Use. You must be legally able to sell the item(s) you list for sale on the Platform and must have all the necessary licenses and permits required for such sale as per applicable laws. All listed items must be kept in stock for successful fulfillment of sales.</p>
          
          <p>The listing description of the item must not be misleading and must describe actual condition of the product. If the item description does not match the actual condition of the item, you agree to refund any amounts that you may have received from the Buyer. You shall not use misleading titles, descriptions or pictures that are not actual representations of the products.
          </p>
          
          <p>You shall not attempt to advertise or offer to sell items which are prohibited or restricted under applicable laws. For a list of products that are prohibited/restricted, please refer to our policies on Prohibited / Restricted Items Policy.
          </p>
          <h3>Returns Policy for Perishable Goods</h3>
          <p>
            Perishable goods such as fresh produce, dairy, and meat products are not eligible for returns to ensure the highest standards of food safety and quality. However, if you receive a perishable item that is not in satisfactory condition, please contact our customer support team within 24 hours of delivery. We may request photographic evidence and will work to resolve the issue promptly, either by providing a refund or replacing the product.
          </p>
          
          <h3>Payment</h3>
          <p>
          While availing any of the payment method(s) available on the Platform, Apala Bajar will not be responsible or assume any liability, whatsoever in respect of any loss or damage arising directly or indirectly to You due to:
          </p>
          <ol>
            <li>Lack of authorization for any transaction(s), or</li>
            <li>Exceeding the preset limit mutually agreed by You and between "Bank(s)", or</li>
            <li>Any payment issues arising out of the transaction, or</li>
            <li>Decline of transaction for any other reason(s).</li>
          </ol>
          <p>
          All payments made against the purchases/services on the Platform by you shall be compulsorily in Indian Rupees acceptable in the Republic of India. The Platform will not facilitate transactions with respect to any other form of currency with respect to the purchases made on Platform.
          </p>
          <p>Before shipping/delivering your order to you, the seller may request you to provide supporting documents (including but not limited to Govt. issued ID and address proof) to establish the ownership of the payment instrument used by you for your purchase. This is done in the interest of providing a safe online shopping environment to Our Users.
          </p>
          
          <h3>Further:
          </h3>
          <p>
          1. Transactions, transaction price and all commercial terms such as delivery, dispatch of products and/or services are as per principal-to-principal bipartite contractual obligations between Buyer and Seller and payment facility is merely used by the Buyer and Seller to facilitate the completion of the transaction. Use of the payment facility shall not render Apala Bajar liable or responsible for the non-delivery, non-receipt, non-payment, damage, breach of representations and warranties, non-provision of after-sales or warranty services or fraud as regards the products and/or services listed on the Platform. Apala Bajar shall not be liable for any dispute or disagreement between Buyers and Sellers.
          </p>
          <p>2. You have specifically authorized Apala Bajar or its service providers to collect, process, facilitate and remit payments and/or the transaction price electronically or through cash on delivery to and from other Users in respect of transactions through payment facility. Your relationship with Apala Bajar is on a principal to principal basis and by accepting these Terms of Use you agree that Apala Bajar is an independent contractor for all purposes, and does not have control of or liability for the products or services that are listed/advertised on the Platform that are paid for by using the payment facility. Apala Bajar does not guarantee the identity of any User nor does it ensure that a Buyer or a Seller will complete a transaction.
          </p>
          <p>3. You understand, accept and agree that the payment facility provided by Apala Bajar is neither a banking nor financial service but is merely a facilitator providing an electronic, automated online electronic payment, receiving payment through Cash On Delivery, collection and remittance facility for the transactions on the Platform using the existing authorized banking infrastructure and credit card payment gateway networks. Further, by providing payment facility, Apala Bajar is neither acting as trustees nor acting in a fiduciary capacity with respect to the transaction or the transaction price.
          </p>

          
          <h2>Dispatch and Delivery
          </h2>
          <p>
          All delivery times mentioned on the website are indicative only and Apala Bajar shall not be held liable for any delay in delivery, if any. Delivery will be done on the address as provided by the Buyer while placing the order. The Buyer is required to be available at the time of delivery to receive the goods. If the delivery could not be completed due to the Buyer not being available at the address, then Apala Bajar will arrange for a redelivery at an additional cost.
          </p>
          
          <h3>Termination
          </h3>
          <ol>
          <li>
          Apala Bajar may suspend or terminate your use of the Platform or any Service if it believes, in its sole and absolute discretion that you have breached, violated, abused, or unethically manipulated or exploited any term of these Terms of Use or anyway otherwise acted unethically.
          </li>
          <li>Notwithstanding Section 1 above, these Terms of Use will survive indefinitely unless and until Apala Bajar chooses to terminate them.
          </li>
          <li>If You or Apala Bajar terminates your use of the Platform or any Service, Apala Bajar may delete any content or other materials relating to your use of the Service and Apala Bajar will have no liability to you or any third party for doing so. However, your transactions details may be preserved by Apala Bajar for purposes of tax or regulatory compliance.
          </li>
          <li>Apala Bajar may unilaterally terminate Your account on any event as mentioned in the Terms of Use. Any credits earned through loyalty or referral programs, Apala Bajar credit, and pending refunds if any will be forfeited in such case.
          </li>
          <li>Returns and refunds for orders placed by the Buyer are as per the Refund Policy. Apala Bajar reserves the right to refuse or cancel orders in its sole discretion at any time.
          </li>
          <li>If you breach any of these Terms of Use, and Apala Bajar chooses not to immediately act, or chooses not to act at all, Apala Bajar will still be entitled to all rights and remedies at any later date, or in any other situation, where you breach these Terms of Use. Apala Bajar does not waive any of its rights. Apala Bajar shall not be liable for any breach of these Terms of Use caused by circumstances beyond its reasonable control.
          </li>
          </ol>
          
          <h3>Governing Law
          </h3>
          <p>
          These Terms of Use and all transactions entered into on or through the Platform and the relationship between You and Apala Bajar shall be governed in accordance with the laws of India without reference to conflict of laws principles.
          </p>
          <p>You agree that all claims, differences and disputes arising under or in connection with or in relation hereto the Platform, the Terms of Use or any transactions entered into on or through the Platform or the relationship between You and Apala Bajar shall be subject to the exclusive jurisdiction of the courts at [City], India and You hereby accede to and accept the jurisdiction of such courts.
          </p>
          <h2>Grievance Officer
          </h2>
         
          <p>
          In accordance with Information Technology Act 2000 and rules made there under, the name and contact details of the Grievance Officer are provided below:
          </p>
          <ul>
          [Officers Details]

          </ul>
          
        
          
          <h2>Contact Information</h2>
          <p>
            If you have any questions or concerns about our return policy, please contact us:
          </p>
          <ul>
            <li>Email: <a href="mailto:aapalabajar@gmail.com">aapalabajar@gmail.com</a></li>
            <li>Customer Service Hotline:+91 9975631919</li>
          </ul>
          <p>
            Our customer service team is available to assist you with any queries or concerns.
          </p>
       
         
        </div>
      );
    };
    
export default TermsOfUse;
